# Generated by Django 4.1.2 on 2022-10-30 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0002_feedback'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feedback',
            new_name='Contact',
        ),
    ]
