# Generated by Django 4.1.2 on 2022-11-01 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0004_blog_detail_delete_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_detail',
            name='phone_number',
        ),
    ]
