# Generated by Django 4.1.2 on 2022-11-01 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0005_remove_blog_detail_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog_detail',
            old_name='first_name',
            new_name='Firstname',
        ),
        migrations.RenameField(
            model_name='blog_detail',
            old_name='last_name',
            new_name='Lastname',
        ),
    ]
